### ISSUE TITLE
Build compose environment using composer

### ISSUE THREAD

**Issue by Pegasuz** [dockerwest/compose-symfony#6]
Add the possibility to create/build the compose-symfony (and later all other compose environments) using composer.

By executing composer create project, we should be able to download the basic compose environment. Create a folder and initialize the environment (uid, gid,..) and start asking questions. 

By asking the right questions we could compose the environment completely on the needs of the project.

We could also add shell/empty Dockerfiles for all used components. We would only add a FROM, providing the correct Dockerwest image, and then add some examples in comment, when people need to customize the image (eg. add more php extensions)

**Comment by BlackIkeEagle** [comment]
There is no need for this, it should be easier to customize the PHP images for stuff like symfony/laravel based projects, see https://github.com/dockerwest/php/issues/2 . And for the general usabilty we should introduce a dockerwest cli tool that can bootstrap/init a project.

I don't think we should build integration with composer itself, since that would require you to have php and composer installed on your host system. Since that is a thing we can avoid with dockerwest your system should be bootstrapped before running composer create-project
